blank_issues_enabled: false
contact_links:
  - name: 📖 Documentația (README)
    url: https://github.com/boogytotyo/engie_ro#readme
    about: Verifică întâi pașii de instalare și notele importante.
  - name: ❓ FAQ
    url: https://github.com/boogytotyo/engie_ro/blob/main/FAQ.md
    about: Întrebări frecvente și răspunsuri rapide.
