name: 💡 Feature request
description: Propune o îmbunătățire sau o funcționalitate nouă
labels: ["enhancement"]
assignees: []
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema pe care vrei să o rezolve
      description: Ce te doare în fluxul actual? (ex. „nu pot vedea X”, „n-am alertă pentru Y”)
      placeholder: "Descrierea problemei"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Soluția propusă
      description: Cum ți-ai imagina să funcționeze?
      placeholder: "Ex. un nou senzor/atribut/opțiune de configurare"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative luate în calcul
      description: Alte idei/variante pe care le-ai considerat.
  - type: textarea
    id: extra
    attributes:
      label: Context suplimentar
      description: Capturi, mockup-uri, exemple JSON, etc.
