name: PR Auto Label
on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure standard labels exist
        uses: actions/github-script@v8
        with:
          script: |
            const wanted = [
              {name: 'bug', color: 'd73a4a', description: 'Defecte / erori'},
              {name: 'enhancement', color: 'a2eeef', description: 'Îmbunătățiri / features'},
              {name: 'documentation', color: '0075ca', description: 'Docs / README'},
              {name: 'ci', color: 'cfd3d7', description: 'CI / workflows'},
              {name: 'dependencies', color: '0366d6', description: 'Actualizări de dependențe'},
              {name: 'integration', color: '6f42c1', description: 'Cod integrare Home Assistant'}
            ];
            const existing = await github.paginate(github.rest.issues.listLabelsForRepo, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 100
            });
            const existingNames = new Set(existing.map(l => l.name));
            for (const w of wanted) {
              if (!existingNames.has(w.name)) {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: w.name,
                  color: w.color,
                  description: w.description
                });
              }
            }

      - name: Apply labels from changed files
        uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true

      - name: Label based on PR title (Conventional Commits)
        uses: actions/github-script@v8
        with:
          script: |
            const title = context.payload.pull_request.title.toLowerCase();
            const labels = [];
            if (title.startsWith('feat') || title.startsWith('feature')) labels.push('enhancement');
            if (title.startsWith('fix')) labels.push('bug');
            if (title.startsWith('docs')) labels.push('documentation');
            if (labels.length) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                labels
              });
            }

      - name: Extra label for Dependabot PRs
        if: github.actor == 'dependabot[bot]'
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: ['dependencies']
            });
